#ifndef COMMUNICATION_COSTANTS
#define COMMUNICATION_COSTANTS

#include <vector>
#include <Arduino.h>

//COMMUNICATION MODE OF SYSTEM
enum class COMMUNICATION_MODE
{
  AP_MODE,
  WIFI_MODE,
  BLUETOOTH_MODE,
  HYBRID_BLUETOOTH_AP,  //NOT AVAIBLE
  HYBRID_BLUETOOTH_WIFI,   //NOT AVAIBLE 
  UNKNOWN_MODE
};

//FUNCTION FOR MAPPING
const COMMUNICATION_MODE communicationModeStringToEnum(String inputString);
const String communicationModeEnumToString(COMMUNICATION_MODE inputEnum);

#endif //COMMUNICATION_COSTANTS